// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCeOnptZQ1U0xmguYi0d7ysN6Ov2lBwY',
    appId: '1:744643645063:web:2146f58849c56a0a51b222',
    messagingSenderId: '744643645063',
    projectId: 'learnflutterr-120d9',
    authDomain: 'learnflutterr-120d9.firebaseapp.com',
    storageBucket: 'learnflutterr-120d9.appspot.com',
    measurementId: 'G-1SXEK0K8CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWx2eJF6oQHqnTzET742wv20ZKKlMuwM',
    appId: '1:744643645063:android:2f316123ea500fd551b222',
    messagingSenderId: '744643645063',
    projectId: 'learnflutterr-120d9',
    storageBucket: 'learnflutterr-120d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-84i_d8Y0jcAO3VLG4OUpOl1s4qOhig',
    appId: '1:744643645063:ios:9678a8aaac9aac7651b222',
    messagingSenderId: '744643645063',
    projectId: 'learnflutterr-120d9',
    storageBucket: 'learnflutterr-120d9.appspot.com',
    iosBundleId: 'com.example.learnfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-84i_d8Y0jcAO3VLG4OUpOl1s4qOhig',
    appId: '1:744643645063:ios:1201abb03de801db51b222',
    messagingSenderId: '744643645063',
    projectId: 'learnflutterr-120d9',
    storageBucket: 'learnflutterr-120d9.appspot.com',
    iosBundleId: 'com.example.learnfirebase.RunnerTests',
  );
}
